pipeline {
    agent any

    environment {
        AWS_PROFILE = 'ecr'
    }

    stages {
        stage("build") {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage("dockerize") {
            steps {
                sh 'mvn compile jib:build'
            }
        }
    }

}